BOOL ChooseFontA(LPCHOOSEFONT lpcf); 
BOOL ChooseFontW(LPCHOOSEFONTW lpcf);
BOOL GetOpenFileNameA(LPOPENFILENAMEA lpofn);
BOOL GetOpenFileNameW(LPOPENFILENAMEW ofn);
BOOL GetSaveFileNameA(LPOPENFILENAMEA lpofn);  
BOOL GetSaveFileNameW(LPOPENFILENAMEW ofn);
BOOL PageSetupDlgA( LPPAGESETUPDLGA );
BOOL PageSetupDlgW( LPPAGESETUPDLGW );
BOOL PrintDlgA( LPPRINTDLGA printdlg);
BOOL PrintDlgW( LPPRINTDLGW printdlg);
DWORD CommDlgExtendedError(void);
HRESULT PrintDlgExA(LPPRINTDLGEXA);
HRESULT PrintDlgExW(LPPRINTDLGEXW);
HWND FindTextA(LPFINDREPLACEA lpFind);
HWND FindTextW(LPFINDREPLACEW lpFind);
HWND ReplaceTextA( LPFINDREPLACEA lpFind);
HWND ReplaceTextW( LPFINDREPLACEW lpFind);
int ChooseColorW(CHOOSECOLORW *lpcc);
short GetFileTitleA(LPCSTR lpFile, LPSTR lpTitle, WORD cbBuf);
short GetFileTitleW(LPCWSTR lpFile, LPWSTR lpTitle, WORD cbBuf);
