ATOM RegisterClassA(void* lpWndClass);
ATOM RegisterClassExA(const WNDCLASSEXA *unnamedParam1);
ATOM RegisterClassExW(const void* lpwcx);
ATOM RegisterClassW(WNDCLASSW* lpWndClass);
BOOL AppendMenuA(HMENU hMenu, UINT uFlags, uintptr_t uIDNewItem, const char* lpNewItem);
BOOL BlockInput(BOOL fBlockIt);
BOOL BringWindowToTop(HWND hWnd);
BOOL CheckDlgButton(HWND hDlg, int nIDButton, UINT uCheck);
BOOL CheckMenuRadioItem(HMENU, UINT, UINT, UINT, UINT);
BOOL CheckRadioButton(HWND hDlg, int nIDFirstButton, int nIDLastButton, int nIDCheckButton);
BOOL CloseClipboard(VOID);
bool CreateCaret(HWND hWnd, HWND hBitmap, int nWidth, int nHeight);
BOOL DestroyCursor(HCURSOR hCursor);
BOOL DestroyIcon(HICON hIcon);
BOOL DestroyWindow(HWND hWnd);
BOOL DragDetect(HWND hwnd, POINT pt); 
BOOL EmptyClipboard(VOID);
BOOL EndDeferWindowPos(HDWP hWinPosInfo);
BOOL EndDialog(HWND hDlg, int nResult);
BOOL EndPaint(HWND hWnd, const PAINTSTRUCT* lpPaint);
BOOL EnumChildWindows(HWND hWndParent, WNDENUMPROC lpEnumFunc, LPARAM lParam);
BOOL EnumThreadWindows(DWORD dwThreadId, WNDENUMPROC lpfn,LPARAM lParam);
BOOL EnumWindows(WNDENUMPROC lpEnumFunc, LPARAM lParam);
bool ExitWindowsEx(uint uFlags, uint dwReason);
BOOL FillRect(void* hDC, void* lprc, HBRUSH hbr);
BOOL FlashWindowEx(FLASHWINFO *pfwi);
BOOL GetClientRect(HWND hWnd, void* lpRect);
BOOL GetCursorPos(LPPOINT lpPoint); 
BOOL GetMenuItemInfoA(HMENU,UINT,BOOL,LPMENUITEMINFOA);
BOOL GetMenuItemRect(HWND hWnd, HMENU hMenu, UINT uItem, RECT* lprcItem);
BOOL GetMessageW(MSG *lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax);
BOOL GetMonitorInfoW(HMONITOR hMonitor, LPMONITORINFO lpmi);
BOOL GetWindowRect(HWND hWnd, RECT *lpRect);
BOOL InSendMessage(VOID);
BOOL InvalidateRgn(HWND hWnd, HRGN hRgn, BOOL bErase);
BOOL IsIconic(HWND hWnd);
BOOL IsWindow(HWND hWnd);
BOOL IsWindowEnabled(HWND hWnd); 
BOOL IsWindowUnicode(HWND hWnd);
BOOL IsWindowVisible(HWND hWnd);
BOOL IsZoomed(HWND hWnd);
BOOL KillTimer(HWND hWnd, UINT_PTR uIDEvent);
BOOL LockWindowUpdate(HWND hWndLock);
BOOL MessageBeep(UINT uType);
BOOL MoveWindow(HWND hWnd, int X, int Y, int nWidth, int nHeight, BOOL bRepaint);
BOOL OpenClipboard(HWND hWndNewOwner); 
BOOL PeekMessageA(struct tagMSG *lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax, UINT wRemoveMsg);
BOOL PeekMessageW(LPMSG lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax, UINT wRemoveMsg);
BOOL PostThreadMessageA(DWORD idThread, UINT Msg, WPARAM wParam, LPARAM lParam);
BOOL PostThreadMessageW(DWORD idThread, DWORD Msg, DWORD wParam, DWORD lParam);
BOOL RedrawWindow(HWND hWnd, const RECT *lprcUpdate, HRGN hrgnUpdate, UINT flags);
BOOL RegisterHotKey(HWND hWnd, int id, UINT fsModifiers, UINT vk);
BOOL SendMessageCallbackA(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam, SENDASYNCPROC lpResultCallBack, DWORD dwData);
BOOL SendMessageCallbackW(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam, SENDASYNCPROC lpResultCallBack, DWORD dwData);
BOOL SendNotifyMessageA(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
BOOL SendNotifyMessageW(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
BOOL SetClipboardData(BOOL format, BOOL hMem);
BOOL SetCursorPos(int X, int Y);
BOOL SetDlgItemInt(HWND hDlg, int nIDDlgItem, UINT uValue, BOOL bSigned);
BOOL SetDlgItemTextA(HWND hDlg, int nIDDlgItem, LPCSTR lpString);
BOOL SetDlgItemTextW(HWND hDlg, int nIDDlgItem, LPCWSTR lpString);
BOOL SetDoubleClickTime(UINT);
BOOL SetForegroundWindow(HWND hWnd);
BOOL SetLayeredWindowAttributes(HWND hWnd, DWORD crKey, BYTE bAlpha, DWORD dwFlags);
BOOL SetMenuItemInfoA(HMENU, UINT, BOOL, LPCMENUITEMINFOA);
BOOL SetMessageQueue(int cMessagesMax);
bool SetProcessDPIAware();
BOOL SetSystemCursor(HCURSOR hcur, DWORD id);
BOOL SetThreadDesktop(HDESK hDesktop);
BOOL SetWindowPos(HWND hWnd, HWND hWndInsertAfter, int X, int Y, int cx, int cy, UINT uFlags);
BOOL SetWindowTextW(HWND hWnd, const wchar_t* lpString);
bool ShowCaret(HWND hWnd);
BOOL ShowWindow(void* hWnd, int nCmdShow);
BOOL SwapMouseButton(BOOL fSwap); 
BOOL SwitchDesktop(HDESK hDesktop);
BOOL SystemParametersInfoA(UINT uiAction, UINT uiParam, PVOID pvParam, UINT fWinIni);
BOOL SystemParametersInfoW(UINT uiAction, UINT uiParam, PVOID pvParam, UINT fWinIni);
BOOL TrackPopupMenu(HMENU, UINT, int, int, int, HWND, void*);
BOOL TranslateMDISysAccel(HWND hWndClient, LPMSG lpMsg);
BOOL TranslateMessage(const MSG *lpMsg);
BOOL UnhookWindowsHook(int nCode, HOOKPROC pfnFilterProc);
BOOL UnhookWindowsHookEx(HHOOK hhk);
BOOL UnhookWinEvent(HWINEVENTHOOK hWinEventHook);
BOOL UnregisterHotKey(HWND hWnd, int id);
BOOL UpdateWindow(HWND hWnd);
BOOL ValidateRect(HWND hWnd, RECT *lpRect);
BOOL ValidateRgn(HWND hWnd, HRGN hRgn);
DWORD GetMessagePos(VOID);
DWORD GetSysColor(int nIndex); 
DWORD GetWindowThreadProcessId(void* hWnd, DWORD* lpdwProcessId);
DWORD MsgWaitForMultipleObjects(DWORD nCount, const HANDLE *pHandles, BOOL bWaitAll, DWORD dwMilliseconds, DWORD dwWakeMask);
HANDLE LoadImageA(HINSTANCE hInst, LPCSTR name, UINT type, int cx, int cy, UINT fuLoad);
HBITMAP LoadBitmapA(HINSTANCE hInstance, LPCSTR lpBitmapName);
HBITMAP LoadBitmapW(HINSTANCE hInstance, LPCWSTR lpBitmapName);
HCURSOR CreateCursor(HINSTANCE hInst, int xHotSpot, int yHotSpot, int nWidth, int nHeight, VOID *pvANDPlane, VOID *pvXORPlane);
HCURSOR LoadCursorA(HINSTANCE hInstance, LPCSTR lpCursorName);
HCURSOR LoadCursorFromFileA(LPCSTR lpFileName);
HCURSOR LoadCursorFromFileW(LPCWSTR lpFileName);
HCURSOR LoadCursorW(HINSTANCE hInstance, LPCWSTR lpCursorName);
HDC BeginPaint(HWND hWnd, PAINTSTRUCT* lpPaint);
HDC GetWindowDC(HWND hWnd);
HDWP BeginDeferWindowPos(int nNumWindows);
HDWP DeferWindowPos(HDWP hWinPosInfo, HWND hWnd, HWND hWndInsertAfter, int x, int y, int cx, int cy, UINT uFlags);
HHOOK SetWindowsHookExA(int idHook, HOOKPROC lpfn,HINSTANCE hmod, DWORD dwThreadId);
HHOOK SetWindowsHookExW(int idHook, HOOKPROC lpfn, HINSTANCE hMod, DWORD dwThreadId);
HICON CreateIcon(HINSTANCE hInstance, int nWidth, int nHeight, BYTE cPlanes, BYTE cBitsPixel, BYTE *lpbANDbits, BYTE *lpbXORbits);
HICON CreateIconFromResource(PBYTE presbits, DWORD dwResSize, BOOL fIcon, DWORD dwVer);
HICON CreateIconFromResourceEx(PBYTE presbits, DWORD dwResSize,BOOL fIcon, DWORD dwVer, int cxDesired, int cyDesired, UINT  Flags);
HICON LoadIconA(HINSTANCE hInstance, LPCSTR lpIconName);
HKL ActivateKeyboardLayout(HKL hkl, UINT Flags); 
HKL LoadKeyboardLayoutA(const char* pwszKLID, unsigned int Flags);
HMENU CreateMenu(void);
HMENU GetMenu(HWND hWnd);
HMONITOR MonitorFromWindow(HWND hWnd, DWORD dwFlags);
HOOKPROC SetWindowsHookA(int nFilterType, HOOKPROC pfnFilterProc);
HOOKPROC SetWindowsHookW(int nFilterType, HOOKPROC pfnFilterProc);
HWINEVENTHOOK SetWinEventHook(DWORD eventMin, DWORD eventMax, HMODULE hmodWinEventProc, WINEVENTPROC pfnWinEventProc, DWORD idProcess, DWORD idThread, DWORD dwFlags);
HWND CreateMDIWindowA(LPSTR lpClassName, LPSTR lpWindowName, DWORD dwStyle, int X, int Y, int nWidth, int nHeight, HWND hWndParent, HINSTANCE hInstance, LPARAM lParam);
HWND CreateMDIWindowW(LPWSTR lpClassName, LPWSTR lpWindowName, DWORD dwStyle, int X, int Y, int nWidth, int nHeight, HWND hWndParent, HINSTANCE hInstance, LPARAM lParam);
HWND CreateWindowExA(DWORD, LPCSTR, LPCSTR, DWORD, int, int, int, int, HWND, void*, void*, void*);
HWND CreateWindowExW(DWORD dwExStyle, LPCWSTR lpClassName, LPCWSTR lpWindowName, DWORD dwStyle, int X, int Y, int nWidth, int nHeight, HWND hWndParent, HMENU hMenu, HINSTANCE hInstance, void* lpParam);
HWND FindWindowA(const char* lpClassName, const char* lpWindowName);
HWND FindWindowExA(HWND hwndParent, HWND hwndChildAfter, LPCSTR lpszClass, LPCSTR lpszWindow);
HWND FindWindowExW(HWND hwndParent, HWND hwndChildAfter, LPCWSTR lpszClass, LPCWSTR lpszWindow);
HWND FindWindowW(LPCWSTR lpClassName, LPCWSTR lpWindowName);
HWND GetActiveWindow(VOID);
HWND GetCapture(VOID);
HWND GetDesktopWindow();
HWND GetDlgItem(HWND hDlg, int nIDDlgItem);
HWND GetForegroundWindow();
HWND GetLastActivePopup(HWND hWnd);
HWND GetParent(HWND hWnd);
HWND GetShellWindow();
HWND GetTopWindow(HWND hWnd);
HWND GetWindow(HWND hWnd, UINT uCmd);
HWND SetClipboardViewer(HWND hWndNewViewer); 
HWND SetParent(HWND hWndChild, HWND hWndNewParent);
HWND WindowFromPoint(POINT Point);
int ChangeDisplaySettingsA(DEVMODE* lpDevMode, unsigned int dwFlags);
int ChangeDisplaySettingsExW(LPCWSTR lpszDeviceName, DEVMODEW *lpDevMode, HWND hwnd, DWORD dwflags, LPVOID lParam);
int CountClipboardFormats(VOID);
int EnumDisplaySettingsA(const char* lpszDeviceName, int iModeNum, DEVMODE* lpDevMode);
int GetClassNameA(HWND hWnd, char* lpClassName, int nMaxCount);
int GetClassNameW(HWND hWnd, WCHAR* lpString, int nMaxCount);
int GetClipboardFormatNameA(UINT format, LPSTR lpszFormatName, int cchMaxCount);
int GetClipboardFormatNameW(UINT format, LPWSTR lpszFormatName, int cchMaxCount);
int GetDlgCtrlID(HWND hWnd);
int GetKeyboardType(int nTypeFlag); 
int GetMessageA(void* lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax);
int GetSystemMetrics(int nIndex);
int GetWindowPlacement(HWND hWnd, WINDOWPLACEMENT* lpwndpl);
int GetWindowTextA(HWND hWnd, char* lpString, int nMaxCount);
int GetWindowTextLengthA(HWND hWnd);
int GetWindowTextW(HWND hWnd, LPCWSTR lpString, int nMaxCount);
int InvalidateRect(HWND, const RECT*, int);
int LookupIconIdFromDirectory(PBYTE presbits, BOOL fIcon);
int LookupIconIdFromDirectoryEx(PBYTE presbits, BOOL fIcon, int cxDesired, int cyDesired, UINT Flags);
int MessageBoxA(void *hWnd, const char *lpText, const char *lpCaption, unsigned int uType);
int MessageBoxExW(void* hWnd, unsigned short* lpText, unsigned short* lpCaption, unsigned int uType, unsigned short wLanguageId);
int MessageBoxW(HWND hWnd, LPCWSTR lpText, LPCWSTR lpCaption, UINT uType);
int ReleaseDC(HWND hWnd, HDC hdc);
int SetMenu(HWND hWnd, HMENU hMenu);
int SetWindowTextA(HWND hWnd, const char* lpString);
INT_PTR DialogBoxParamA(HINSTANCE hInstance, LPCSTR lpTemplateName, HWND hWndParent, DLGPROC lpDialogFunc, LPARAM dwInitParam);
long BroadcastSystemMessage(DWORD dwFlags, LPDWORD lpdwRecipients, UINT uiMessage, WPARAM wParam, LPARAM lParam);
LONG CallNextHookEx(HHOOK hhk, int nCode, uintptr_t wParam, uintptr_t lParam);
LONG GetMessageExtraInfo(VOID);
LONG GetMessageTime(VOID);
LONG GetWindowLongA(HWND hWnd, int nIndex);
LONG SetWindowLongA(HWND hWnd, int nIndex, LONG dwNewLong);
LONG SetWindowLongA(HWND hWnd, int nIndex, LONG dwNewLong);
LPARAM SetMessageExtraInfo(LPARAM lParam);
LRESULT CallWindowProcA(WNDPROC lpPrevWndFunc, HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
LRESULT DefWindowProcA(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
LRESULT DefWindowProcW(HWND hWnd, unsigned int uMsg, WPARAM wParam, LPARAM lParam);
LRESULT DispatchMessageA(void* lpMsg);
LRESULT DispatchMessageW(const MSG* lpMsg);
LRESULT SendMessageA(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
LRESULT SendMessageTimeoutA(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam, UINT fuFlags, UINT uTimeout, LPDWORD lpdwResult);
LRESULT SendMessageTimeoutW(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam, UINT fuFlags, UINT uTimeout, LPDWORD lpdwResult);
LRESULT SendMessageW(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
short GetAsyncKeyState(int vKey);
UINT ArrangeIconicWindows(HWND hWnd);
UINT EnumClipboardFormats(UINT format);
UINT GetDlgItemInt(HWND hDlg, int nIDDlgItem, BOOL *lpTranslated, BOOL bSigned);
UINT GetDoubleClickTime(VOID);
UINT GetDpiForSystem();
UINT GetDpiForWindow(HWND hWnd);
UINT SendInput(UINT nInputs, INPUT* pInputs, int cbSize);
UINT_PTR SetTimer(HWND hWnd, UINT_PTR nIDEvent, UINT uElapse, TIMERPROC lpTimerFunc );
void keybd_event(unsigned char bVk, unsigned char bScan, unsigned long dwFlags, unsigned long dwExtraInfo);
void mouse_event(DWORD dwFlags, DWORD dx, DWORD dy, DWORD dwData, ULONG_PTR dwExtraInfo);
void mouse_event(unsigned long dwFlags, unsigned long dx, unsigned long dy, unsigned long dwData, unsigned long dwExtraInfo);
void PostQuitMessage(int nExitCode);
VOID SetDebugErrorLevel(DWORD dwLevel);
VOID SetLastErrorEx(DWORD dwErrCode, DWORD dwType);
void* CreatePopupMenu();
void* GetDC(HWND hWnd);
void* SetWindowLongPtrA(HWND, int, void*);
WORD CascadeWindows(HWND hwndParent, UINT wHow, RECT* lpRect, UINT cKids,  const HWND lpKids);
WORD TileWindows(HWND hwndParent, UINT wHow, RECT* lpRect, UINT cKids, const HWND lpKids);
INT_PTR DialogBoxIndirectParamA(HINSTANCE hInst, LPCDLGTEMPLATE hDialogTemplate, HWND hWndParent, void* lpDialogFunc, long dwInitParam);
int DialogBoxIndirectParamW(void* hInst, void* lpTpl, void* hParent, DLGPROC proc, LPARAM param);
int GetDlgItemTextW(void* hDlg, int id, wchar_t* buf, int max);
void* SetFocus(void* hWnd);
short GetKeyState(int nVirtKey);
int ShowCursor(int bShow);
int DrawTextA(HDC hDC, LPCSTR lpString, int nCount, LPRECT lpRect, UINT uFormat);

/* Declarations for calls WindowsAPI already makes. */
BOOL ClientToScreen(HWND hWnd, POINT* lpPoint);


BOOL DrawIconEx(HANDLE hdc, int xLeft, int yTop, HANDLE hIcon, int cxWidth, int cyWidth, UINT istepIfAniCur, HBRUSH hbrFlickerFreeDraw, UINT diFlags);

BOOL EnableWindow(HWND hWnd, BOOL bEnable);

HANDLE GetClipboardData(UINT uFormat);

BOOL GetLastInputInfo(PVOID plii);

BOOL IsClipboardFormatAvailable(UINT format);

BOOL LockWorkStation();

UINT RegisterClipboardFormatA(LPCSTR lpszFormat);

BOOL ScreenToClient(HWND hWnd, POINT* lpPoint);

HCURSOR SetCursor(HCURSOR hCursor);

short VkKeyScanA(char ch);

DWORD GetClipboardSequenceNumber(VOID);
