<?php

/**
 * License - Onetone Framework
 *
 * @copyright  Copyright (C) Onetoneframework (tactics6655@gmail.com)
 * @license    AGPL 3.0
 */

declare(strict_types=1);

namespace Clover\Plugin;

use Clover\Classes\ClientURL;
use Clover\Classes\Data\ArrayObject;
use Clover\Classes\Data\JSONHandler;

class Kakao
{
    private string $clientId;
    private string $clientSecret;
    private string $redirectUrl;
    private string $state;

    private const AUTH_BASE  = 'https://kauth.kakao.com/';
    private const API_BASE   = 'https://kapi.kakao.com/';

    /**
     * Set the Kakao REST API key (client ID).
     */
    public function setClientId(string $clientId): void
    {
        $this->clientId = $clientId;
    }

    /**
     * Set the Kakao client secret.
     */
    public function setClientSecret(string $clientSecret): void
    {
        $this->clientSecret = $clientSecret;
    }

    /**
     * Set the OAuth redirect URI registered in Kakao Developers Console.
     */
    public function setRedirectUrl(string $url): void
    {
        $this->redirectUrl = $url;
    }

    /**
     * Return the state value generated by the last getLoginUrl() call (for CSRF prevention).
     */
    public function getState(): ?string
    {
        return $this->state ?? null;
    }

    /**
     * Build and return the Kakao OAuth authorization URL.
     *
     * Supported $options keys:
     *   prompt          string   login | none | select_account — controls the consent screen
     *   login_hint      string   Pre-fill the email field on the login screen
     *   service_terms   string   Comma-separated service term tags to request
     *   nonce           string   Replay attack prevention value for OpenID Connect
     */
    public function getLoginUrl(?string $scope = null, array $options = []): string
    {
        $this->state = md5((string) mt_rand(111111111, 999999999));

        $params = [
            'client_id'     => $this->clientId,
            'redirect_uri'  => $this->redirectUrl,
            'response_type' => 'code',
            'state'         => $this->state,
        ];

        if ($scope !== null) {
            $params['scope'] = $scope;
        }

        foreach (['prompt', 'login_hint', 'service_terms', 'nonce'] as $key) {
            if (isset($options[$key])) {
                $params[$key] = $options[$key];
            }
        }

        return self::AUTH_BASE . 'oauth/authorize?' . http_build_query($params);
    }

    /**
     * Exchange the authorization code for an access token.
     *
     * Response fields: token_type, access_token, expires_in, refresh_token, refresh_token_expires_in, scope, id_token
     */
    public function getToken(string $code): ArrayObject
    {
        return $this->postFormRequest(self::AUTH_BASE . 'oauth/token', [
            'grant_type'    => 'authorization_code',
            'client_id'     => $this->clientId,
            'client_secret' => $this->clientSecret,
            'redirect_uri'  => $this->redirectUrl,
            'code'          => $code,
        ]);
    }

    /**
     * Refresh the access token using a refresh token.
     */
    public function refreshToken(string $refreshToken): ArrayObject
    {
        return $this->postFormRequest(self::AUTH_BASE . 'oauth/token', [
            'grant_type'    => 'refresh_token',
            'client_id'     => $this->clientId,
            'client_secret' => $this->clientSecret,
            'refresh_token' => $refreshToken,
        ]);
    }

    /**
     * Revoke the access token and log the user out of Kakao.
     */
    public function logout(string $accessToken): ArrayObject
    {
        return $this->postBearerRequest(self::API_BASE . 'v1/user/logout', [], $accessToken);
    }

    /**
     * Unlink the user from the Kakao app (revoke all tokens and delete the connection).
     */
    public function unlink(string $accessToken): ArrayObject
    {
        return $this->postBearerRequest(self::API_BASE . 'v1/user/unlink', [], $accessToken);
    }

    /**
     * Get the profile of the authenticated user.
     *
     * Response fields: id, connected_at, kakao_account (profile, email, age_range, birthday, etc.)
     */
    public function getProfile(string $accessToken): ArrayObject
    {
        return $this->getBearerRequest(self::API_BASE . 'v2/user/me', $accessToken);
    }

    /**
     * Update the user's service profile (nickname, profile image).
     * Requires the profile_nickname or profile_image scope.
     */
    public function updateProfile(string $accessToken, array $properties): ArrayObject
    {
        return $this->postBearerRequest(self::API_BASE . 'v1/user/update_profile', [
            'properties' => json_encode($properties),
        ], $accessToken, false);
    }

    /**
     * Get the list of friends who have also connected the same Kakao app.
     * Requires the friends scope.
     *
     * Supported $options keys:
     *   offset      int    Pagination offset
     *   limit       int    Max results (max 100, default 10)
     *   order       string asc | desc
     *   friend_order string favorite | nickname
     */
    public function getFriends(string $accessToken, array $options = []): ArrayObject
    {
        $query = !empty($options) ? '?' . http_build_query($options) : '';
        return $this->getBearerRequest(self::API_BASE . 'v1/api/talk/friends' . $query, $accessToken);
    }

    /**
     * Send a KakaoTalk message to the authenticated user themselves.
     * $template must be a valid Kakao message template object (feed, list, location, commerce, text, etc.).
     */
    public function sendMessageToMe(string $accessToken, array $template): ArrayObject
    {
        return $this->postBearerRequest(self::API_BASE . 'v2/api/talk/memo/default/send', [
            'template_object' => json_encode($template),
        ], $accessToken, false);
    }

    /**
     * Send a KakaoTalk message to a specific friend.
     * Requires the talk_message scope. The receiver must also have the app installed.
     *
     * $receiverUuids: array of friend UUIDs obtained from getFriends().
     */
    public function sendMessageToFriends(string $accessToken, array $receiverUuids, array $template): ArrayObject
    {
        return $this->postBearerRequest(self::API_BASE . 'v1/api/talk/friends/message/default/send', [
            'receiver_uuids'  => json_encode($receiverUuids),
            'template_object' => json_encode($template),
        ], $accessToken, false);
    }

    /**
     * Get a list of scopes (permissions) the user has consented to.
     */
    public function getScopedUserInfo(string $accessToken): ArrayObject
    {
        return $this->getBearerRequest(self::API_BASE . 'v2/user/scopes', $accessToken);
    }

    /**
     * Revoke specific consent scopes from the user.
     * $scopes: array of scope names to revoke.
     */
    public function revokeScopes(string $accessToken, array $scopes): ArrayObject
    {
        return $this->postBearerRequest(self::API_BASE . 'v2/user/revoke/scopes', [
            'scopes' => json_encode($scopes),
        ], $accessToken, false);
    }

    /**
     * Send a POST request with form-encoded body and return decoded response.
     */
    private function postFormRequest(string $url, array $fields): ArrayObject
    {
        $cURL = new ClientURL($url);
        $cURL->option
            ->setURL($url)
            ->setSSLVerifyPeer(false)
            ->setSSLVerifyHost(false)
            ->setReturnTransfer()
            ->setPostMethod()
            ->setHeader('Content-Type', 'application/x-www-form-urlencoded;charset=utf-8')
            ->setPostFields($fields);

        return JSONHandler::decode($cURL->execute(), true);
    }

    /**
     * Send a Bearer-authenticated POST request and return decoded response.
     * Pass $json=false to send as form-encoded instead of JSON.
     */
    private function postBearerRequest(string $url, array $fields, string $accessToken, bool $json = true): ArrayObject
    {
        $cURL = new ClientURL($url);
        $cURL->option
            ->setURL($url)
            ->setSSLVerifyPeer(false)
            ->setSSLVerifyHost(false)
            ->setReturnTransfer()
            ->setPostMethod()
            ->setHeader('Authorization', 'Bearer ' . $accessToken);

        if ($json) {
            $cURL->option
                ->setHeader('Content-Type', 'application/json;charset=utf-8')
                ->setPostFields($fields);
        } else {
            $cURL->option
                ->setHeader('Content-Type', 'application/x-www-form-urlencoded;charset=utf-8')
                ->setPostFields($fields);
        }

        return JSONHandler::decode($cURL->execute(), true);
    }

    /**
     * Send a Bearer-authenticated GET request and return decoded response.
     */
    private function getBearerRequest(string $url, string $accessToken): ArrayObject
    {
        $cURL = new ClientURL($url);
        $cURL->option
            ->setURL($url)
            ->setSSLVerifyPeer(false)
            ->setSSLVerifyHost(false)
            ->setReturnTransfer()
            ->setHeader('Authorization', 'Bearer ' . $accessToken);

        return JSONHandler::decode($cURL->execute(), true);
    }
}
