<?php

declare(strict_types=1);

/**
 * License - Onetone Framework
 *
 * @copyright  Copyright (C) Onetoneframework (tactics6655@gmail.com)
 * @license    AGPL 3.0
 */

namespace Clover\Plugin;

use Clover\Classes\ClientURL;
use Clover\Classes\Data\ArrayObject;
use Clover\Classes\Data\JSONHandler;

class Line
{
    private string $clientId;
    private string $clientSecret;
    private string $redirectUrl;
    private string $state;
    private ?string $nonce = null;
    private ?string $codeVerifier = null;

    /**
     * Set LINE channel ID.
     */
    public function setClientId(string $id): void
    {
        $this->clientId = $id;
    }

    /**
     * Set LINE channel secret.
     */
    public function setClientSecret(string $secret): void
    {
        $this->clientSecret = $secret;
    }

    /**
     * Set OAuth callback URL registered in LINE Developers Console.
     */
    public function setRedirectUrl(string $url): void
    {
        $this->redirectUrl = $url;
    }

    /**
     * Generate a PKCE code_verifier and store it internally.
     * Must be called before getLoginUrl() if using PKCE.
     */
    public function generateCodeVerifier(): string
    {
        $this->codeVerifier = rtrim(strtr(base64_encode(random_bytes(32)), '+/', '-_'), '=');
        return $this->codeVerifier;
    }

    /**
     * Return the stored code_verifier (pass to getToken() when using PKCE).
     */
    public function getCodeVerifier(): ?string
    {
        return $this->codeVerifier;
    }

    /**
     * Return the state value generated by the last getLoginUrl() call.
     * Compare this against the state parameter returned to the callback URL to prevent CSRF.
     */
    public function getState(): ?string
    {
        return $this->state ?? null;
    }

    /**
     * Return the nonce generated by the last getLoginUrl() call.
     * Pass to verifyIdToken() to prevent replay attacks.
     */
    public function getNonce(): ?string
    {
        return $this->nonce;
    }

    /**
     * Build and return the LINE Login authorization URL.
     *
     * Supported $options keys:
     *   prompt              string   consent | none | login
     *   bot_prompt          string   normal | aggressive — show "Add friend" option on consent screen
     *   ui_locales          string   BCP 47 language tags (e.g. "ja en")
     *   max_age             int      max seconds since last authentication
     *   disable_auto_login  bool     true to disable auto login
     *   pkce                bool     true to attach code_challenge (calls generateCodeVerifier internally)
     */
    public function getLoginUrl(?string $scope = null, array $options = []): string
    {
        $this->state = md5((string) mt_rand(111111111, 999999999));
        $this->nonce = md5((string) mt_rand(111111111, 999999999));

        $params = [
            'response_type' => 'code',
            'client_id' => $this->clientId,
            'redirect_uri' => $this->redirectUrl,
            'state' => $this->state,
            'scope' => $scope ?? 'profile openid',
            'nonce' => $this->nonce,
        ];

        foreach (['prompt', 'bot_prompt', 'ui_locales', 'max_age'] as $key) {
            if (isset($options[$key])) {
                $params[$key] = $options[$key];
            }
        }

        if (isset($options['disable_auto_login'])) {
            $params['disable_auto_login'] = $options['disable_auto_login'] ? 'true' : 'false';
        }

        if (!empty($options['pkce'])) {
            $verifier = $this->generateCodeVerifier();
            $params['code_challenge'] = rtrim(strtr(base64_encode(hash('sha256', $verifier, true)), '+/', '-_'), '=');
            $params['code_challenge_method'] = 'S256';
        }

        return 'https://access.line.me/oauth2/v2.1/authorize?' . http_build_query($params);
    }

    /**
     * Exchange the authorization code for an access token.
     * Pass $codeVerifier when the authorization request used PKCE.
     *
     * Response fields: access_token, expires_in, id_token, refresh_token, scope, token_type
     */
    public function getToken(string $code, ?string $codeVerifier = null): ArrayObject
    {
        $fields = [
            'grant_type' => 'authorization_code',
            'code' => $code,
            'redirect_uri' => $this->redirectUrl,
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret,
        ];

        if ($codeVerifier !== null) {
            $fields['code_verifier'] = $codeVerifier;
        }

        return $this->postRequest('https://api.line.me/oauth2/v2.1/token', $fields);
    }

    /**
     * Issue a new access token using a refresh token.
     * Refresh tokens are valid for 90 days from the time the access token was issued.
     */
    public function refreshToken(string $refreshToken): ArrayObject
    {
        return $this->postRequest('https://api.line.me/oauth2/v2.1/token', [
            'grant_type' => 'refresh_token',
            'refresh_token' => $refreshToken,
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret,
        ]);
    }

    /**
     * Revoke an access token.
     * Call this when the user logs out and delete all stored user data afterward.
     */
    public function revokeToken(string $accessToken): ArrayObject
    {
        return $this->postRequest('https://api.line.me/oauth2/v2.1/revoke', [
            'access_token' => $accessToken,
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret,
        ]);
    }

    /**
     * Verify whether an access token is valid.
     * Returns channel ID, scope, and expiry information.
     */
    public function verifyToken(string $accessToken): ArrayObject
    {
        $url = 'https://api.line.me/oauth2/v2.1/verify?access_token=' . urlencode($accessToken);

        $cURL = new ClientURL($url);
        $cURL->option
            ->setURL($url)
            ->setSSLVerifyPeer(false)
            ->setSSLVerifyHost(false)
            ->setReturnTransfer();

        return JSONHandler::decode($cURL->execute(), true);
    }

    /**
     * Verify an ID token via the LINE server.
     * Pass the nonce that was used in the authorization request to prevent replay attacks.
     *
     * Response fields: iss, sub (userId), aud, exp, iat, nonce, amr, name, picture, email
     */
    public function verifyIdToken(string $idToken, ?string $nonce = null): ArrayObject
    {
        $fields = [
            'id_token' => $idToken,
            'client_id' => $this->clientId,
        ];

        if ($nonce !== null) {
            $fields['nonce'] = $nonce;
        }

        return $this->postRequest('https://api.line.me/oauth2/v2.1/verify', $fields);
    }

    /**
     * Get the profile of the authenticated user.
     * Requires an access token with the profile scope.
     *
     * Response fields: userId, displayName, pictureUrl, statusMessage
     */
    public function getProfile(string $accessToken): ArrayObject
    {
        return $this->getRequest('https://api.line.me/v2/profile', $accessToken);
    }

    /**
     * Get the friendship status between the user and the LINE Official Account
     * linked to this channel. Requires bot_prompt to have been used during login.
     *
     * Response fields: friendFlag (bool)
     */
    public function getFriendshipStatus(string $accessToken): ArrayObject
    {
        return $this->getRequest('https://api.line.me/friendship/v1/status', $accessToken);
    }

    /**
     * Decode an ID token payload locally without server-side signature verification.
     * For production environments, use verifyIdToken() instead.
     */
    public function decodeIdToken(string $idToken): ?array
    {
        $parts = explode('.', $idToken);
        if (count($parts) !== 3) {
            return null;
        }

        $payload = $parts[1];
        $payload .= str_repeat('=', (4 - strlen($payload) % 4) % 4);
        $decoded = base64_decode(strtr($payload, '-_', '+/'));

        if ($decoded === false) {
            return null;
        }

        $data = json_decode($decoded, true);
        return is_array($data) ? $data : null;
    }

    /**
     * Send a POST request with form-encoded fields and return decoded JSON.
     */
    private function postRequest(string $url, array $fields): ArrayObject
    {
        $cURL = new ClientURL($url);
        $cURL->option
            ->setURL($url)
            ->setSSLVerifyPeer(false)
            ->setSSLVerifyHost(false)
            ->setReturnTransfer()
            ->setPostMethod()
            ->setHeader('Content-Type', 'application/x-www-form-urlencoded')
            ->setPostFields($fields);

        return JSONHandler::decode($cURL->execute(), true);
    }

    /**
     * Send a Bearer-authenticated GET request and return decoded JSON.
     */
    private function getRequest(string $url, string $accessToken): ArrayObject
    {
        $cURL = new ClientURL($url);
        $cURL->option
            ->setURL($url)
            ->setSSLVerifyPeer(false)
            ->setSSLVerifyHost(false)
            ->setReturnTransfer()
            ->setHeader('Authorization', 'Bearer ' . $accessToken);

        return JSONHandler::decode($cURL->execute(), true);
    }
}
